### ISSUE TITLE
Vytvorenie katalógu požiadaviek podľa štandardu IEEE/ISO/IEC 29148

### ISSUE THREAD

**Issue by virtualmachine44** [TIS2024-FMFI/theater-archive#1]
Spísanie všetkých požiadaviek od zadávateľa a potvrdenie správnosti daných požiadaviek.

Veronika Bojda - 1. Úvod
Samuel Dubný - 3. Špecifikácia požiadaviek
Johanka Jakubove - 2. Všeobecný popis: 2.3 Charakteristika používateľov, 2.4 Predpoklady, závislosti a obmedzenia
Martin Vitan - 2. Všeobecný popis: 2.1 Perspektíva systému, 2.2 Funkcie systému

**Comment by johankajakubove** [comment]
Dokumnet: 
https://docs.google.com/document/d/1iADtUKjdHLSoxKq38sxGW2OCE9yGBVIlvMre49xBLUE/edit

**Comment by virtualmachine44** [comment]
Skutočné rozdelenie úloh:

Veronika Bojda - 1. Úvod
Samuel Dubný - 2. Všeobecný popis: 2.3 Perspektíva systému, 2.4 Funkcie systému
Johanka Jakubove - 2. Všeobecný popis: 2.3 Charakteristika používateľov, 2.4 Predpoklady, závislosti a obmedzenia, 3. špecifikácia požiadaviek
Martin Vitan - 2. Všeobecný popis: 2.1 Perspektíva systému, 2.2 Funkcie systému

**Comment by johankajakubove** [comment]
Dostali sme poznámky od pani Karkalíkovej, podľa ktorých treba katalóg upraviť.

**Comment by virtualmachine44** [comment]
Dnes pani Karkalíková poslala mailom finálne zmeny ktoré treba zahrnúť v katalógu požiadaviek.

**Comment by virtualmachine44** [comment]
Na osobnom stretnutí pani Karkalíková požiadala o ešte jednu drobnú úpravu vo formulároch, táto zmena bola na mieste implementovaná a katalóg bol osobne odsúhlasený. Už sa nebudú vykonávať žiadne zmeny. Z dôvodu vysokej vyťaženosti oficiálne schválenie pani Karkalíková pošle prostrednícvom emailu do konca tohto týždňa.

**Comment by virtualmachine44** [comment]
Katalóg požiadaviek je schválený zadávateľkou.
