### ISSUE TITLE
Zoznamovanie sa s  vybranými technológiami

### ISSUE THREAD

**Issue by johankajakubove** [TIS2024-FMFI/theater-archive#10]
Skúšanie, inštalácia a pozeranie tutoriálov týkajúcich sa Djanga, Reactu a PostgreSQL.

**Comment by johankajakubove** [comment]
https://www.geeksforgeeks.org/django-tutorial/

**Comment by MartinVitan** [comment]
Ja som si kúpil tento kurz pre začiatočníkov, ktorý vyučuje základy práce s Djangom.
https://www.udemy.com/course/django-complete-course/
