### ISSUE TITLE
Dátový model

### ISSUE THREAD

**Issue by johankajakubove** [TIS2024-FMFI/theater-archive#12]
### Poznámky: ###
- podrobný dátový model perzistentných údajov, formátov súborov, komunikačných protokolov
- napr. [pgadmin](https://www.youtube.com/watch?v=2pxVCzRFGeg)

**Comment by johankajakubove** [comment]
Rozhodnutie na stretnutí: Obrázky budú uložené ako relatívna cesta, nie BLOB.

**Comment by virtualmachine44** [comment]
Nová verzia dátoveho modelu:

https://app.moqups.com/MP1VLTx9VNqgpYGRO9Vkbq7pO6LNcIWf/view/page/ad64222d5

**Comment by pavelpetrovic** [comment]
![Image](https://github.com/user-attachments/assets/ef2bcfa7-ecfb-4548-91cf-3c29585d2a05)
