### ISSUE TITLE
Návrh implementácie

### ISSUE THREAD

**Issue by johankajakubove** [TIS2024-FMFI/theater-archive#14]
### Poznámky ###
- zrozumiteľný a jednoznačný návrh implementácie, podľa ktorého sa dá aplikácia vyvinúť a ktorý bude obsahovať: UML component diagram, UML class diagram, a aspoň jeden z dvojice UML state a UML sequence diagram, zrozumiteľne vysvetlenú architektúru, rozdelenie na časti (moduly) a ich interfejsy, využité technológie, cieľové prostredie nasadenia do prevádzky
- spoločne navrhneme architektúru

**Comment by virtualmachine44** [comment]
Link na rozpracovaný návrh:

https://docs.google.com/document/d/1a0AHJSNrcMThbcQyf70WIu5AQADac2KQtlHURQfSf5k/edit?tab=t.0

**Comment by johankajakubove** [comment]
Link na diagramy: https://app.moqups.com/vDKhunDjK1Pf8xQBluDcUAbvfILub0oK/view/page/a3c9e721a

**Comment by pavelpetrovic** [comment]
v zdielanom dokumente navrh prosim vytvorit rozumne nadpisy kapitol, aby ste ich mohli co najskor vyplnit obsahom
