### ISSUE TITLE
Stretnutie s technikom

### ISSUE THREAD

**Issue by johankajakubove** [TIS2024-FMFI/theater-archive#4]

**Comment by virtualmachine44** [comment]
Tabulka s kontaktom na všetkých účastníkov projektu:
https://docs.google.com/spreadsheets/d/1MYl2saos2oybZXnaQo2OMW_TKAQpn19azTKyZ5oFZI8/edit?gid=0#gid=0

**Comment by johankajakubove** [comment]
Stretnutie prebehlo -> dohodli sme si meeting v najblližších dňoch s pani Karkalíkovou - čakáme na odpoveď s termínom.

**Comment by virtualmachine44** [comment]
Viac informacie v zápisniciach 4 a 5.

**Comment by johankajakubove** [comment]
Otázky na stretnutie:

https://docs.google.com/document/d/1o0cENjuqtuzF4hLiazk0TDlzDaTNMrSh0toFq8C-RQY/edit?tab=t.0
