### ISSUE TITLE
Vizuálne mockupy

### ISSUE THREAD

**Issue by johankajakubove** [TIS2024-FMFI/theater-archive#8]
Momentálne dohadujeme čas a dátum stretnutia, ktoré sa bude týkať tejto témy, rozdelenia úloh a výberu technológie.

**Comment by RoscaN03** [comment]
Všetci sme si vyskúšali prácu s týmto nástrojom a stihli sme už urobiť prvé návrhy našej stránky.

**Comment by virtualmachine44** [comment]
Prvý pokus návrhu hlavnej stránky:
https://app.moqups.com/lKnwybrTryHNZkH2YQmixXLwJzqZFXr3/edit/page/aa4c7dde7

**Comment by virtualmachine44** [comment]
Prišli pripomienky mailom. Na sobotnom stretnutí tímu ich prejdeme a zapracujeme.

**Comment by virtualmachine44** [comment]
Kvôli nedostatku miesta pokračujeme tu:

https://app.moqups.com/BCGOnzy3VPbZhkusDQgoukh1AG55qAaW/view/page/a2e372b67
